---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app-deployment
  namespace: default  # Aquí especifica el namespace deseado
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-app
          image: anteo90/next3 
          ports:
            - containerPort: 3000