---

apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
  namespace: default  # Aquí especifica el namespace deseado
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30003
  selector:
    app: nextjs-app