
- name: Instalar paqueteria
  apt:
    name:
      - ca-certificates
      - gnupg
    state: present

- name: Añadir GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Añadir repositorio Docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update System
  apt: 
    name: "*"
    state: latest

- name: Instalar Docker Engine
  apt:  
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add user to docker group
  ansible.builtin.shell: |
    sudo usermod -aG docker {{ ansible_user }}

- name: Reload Docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
